### ISSUE TITLE
Error with cli Bones

### ISSUE THREAD

**Issue by dmoraCdev** [wpbones/WPBones#5]
Thank you very much for your work.
I'm testing your framework, and I have this problem when I try to run the "php bones" commands.
I think my problem may be the PHP version, I'm using PHP 7.
You could help me please.

![image](https://user-images.githubusercontent.com/32403682/31039130-5a61ce86-a538-11e7-815d-219da098d367.png)

**Comment by gfazioli** [comment]
@dmoraCdev Hi there, thank you for your support.
I think that the issue is due to your env. You should use the WordPress container, I mean, you should be in the shell of WordPress because `php bones` is using WordPress connect.

> The php bones command, should be run from your WordPress environment (into the Vagrant or Valet) because it will load WordPress. Also, make sure to install git and composer in your WordPress environment. Instead, in your host machine (Mac or PC) you can install npm. It is used only by gulp.

Could you give me more detail about your environment?

For more info have a look here https://github.com/wpbones/WPBones/wiki/requirements
